name: CheckForSquadServerUpdate
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Pull repository
      uses: actions/checkout@v2
      with:
        repository: Deutsche-Squad-Gemeinschaft/gists
        token: ${{ secrets.PERSONAL_TOKEN }}
        
    - name: Setup python
      uses: actions/setup-python@v2
      
    - name: Install SteamPython
      run: python -m pip --disable-pip-version-check install -Uq steam[client]
      
    - name: Check for updates
      id: updatecheck
      run: echo ::set-output name=found::$(python ./.github/CheckForSquadServerUpdate.py)
      
    - name: Dispatch UpdateSquadServerData workflow
      if: steps.updatecheck.outputs.found == 'Update found.' && ${{! test -f "tmp/UpdateSquadServerData"}}
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: UpdateSquadServerData
        repo: Deutsche-Squad-Gemeinschaft/gists
        token: ${{ secrets.PERSONAL_TOKEN }}
